import type { Asset, SavingsPlan, WishItem } from './types';
import { daysAgoISO } from './calc';

export function demoAssets(): Asset[] {
  return [
    {
      id: 'a-macbook',
      name: 'MacBook Pro',
      category: 'digital',
      status: 'active',
      purchasePrice: 11750,
      purchaseDate: daysAgoISO(1020),
      targetDailyCost: 10.3,
      expectedDays: 1140,
      imageKey: 'macbook',
      starred: true,
      tags: ['主力'],
    },
    {
      id: 'a-iphone15',
      name: 'iPhone 15 Pro',
      category: 'digital',
      status: 'active',
      purchasePrice: 6850,
      purchaseDate: daysAgoISO(634),
      targetDailyCost: 8.8,
      expectedDays: 776,
      imageKey: 'iphone',
      starred: true,
      tags: ['主力'],
    },
    {
      id: 'a-watch',
      name: 'Apple Watch Ultra',
      category: 'digital',
      status: 'active',
      purchasePrice: 2300,
      purchaseDate: daysAgoISO(325),
      targetDailyCost: 5,
      expectedDays: 460,
      imageKey: 'watch',
    },
    {
      id: 'a-airpods',
      name: 'AirPods Pro',
      category: 'digital',
      status: 'active',
      purchasePrice: 1699,
      purchaseDate: daysAgoISO(180),
      targetDailyCost: 6,
      expectedDays: 283,
      imageKey: 'earbuds',
    },
    {
      id: 'a-iphone17',
      name: '17 Pro Max',
      category: 'digital',
      status: 'active',
      purchasePrice: 8999,
      purchaseDate: daysAgoISO(908),
      targetDailyCost: 9.9,
      expectedDays: 909,
      imageKey: 'iphone',
      starred: true,
    },
    {
      id: 'a-headphones',
      name: 'Max 头戴耳机',
      category: 'digital',
      status: 'active',
      purchasePrice: 3999,
      purchaseDate: daysAgoISO(410),
      targetDailyCost: 8,
      expectedDays: 500,
      imageKey: 'headphones',
    },
    {
      id: 'a-tablet',
      name: 'Air 平板',
      category: 'digital',
      status: 'active',
      purchasePrice: 4799,
      purchaseDate: daysAgoISO(220),
      targetDailyCost: 10,
      expectedDays: 480,
      imageKey: 'tablet',
    },
    {
      id: 'a-speaker',
      name: 'Home 音箱',
      category: 'home',
      status: 'active',
      purchasePrice: 2299,
      purchaseDate: daysAgoISO(540),
      targetDailyCost: 4,
      expectedDays: 575,
      imageKey: 'speaker',
    },
    {
      id: 'a-camera',
      name: '口袋相机',
      category: 'digital',
      status: 'retired',
      purchasePrice: 5680,
      purchaseDate: daysAgoISO(800),
      retiredDate: daysAgoISO(40),
      targetDailyCost: 8,
      expectedDays: 710,
      imageKey: 'camera',
      note: '吃灰退役，准备挂闲鱼',
    },
    {
      id: 'a-vr',
      name: '混合现实头显',
      category: 'digital',
      status: 'retired',
      purchasePrice: 2999,
      purchaseDate: daysAgoISO(420),
      retiredDate: daysAgoISO(30),
      targetDailyCost: 10,
      expectedDays: 300,
      imageKey: 'vr',
    },
    {
      id: 'a-turntable',
      name: '黑胶唱机',
      category: 'home',
      status: 'retired',
      purchasePrice: 1880,
      purchaseDate: daysAgoISO(900),
      retiredDate: daysAgoISO(60),
      targetDailyCost: 3,
      expectedDays: 627,
      imageKey: 'turntable',
    },
    {
      id: 'a-controller',
      name: '游戏手柄',
      category: 'blindbox',
      status: 'retired',
      purchasePrice: 599,
      purchaseDate: daysAgoISO(200),
      retiredDate: daysAgoISO(10),
      targetDailyCost: 2,
      expectedDays: 300,
      imageKey: 'controller',
    },
    {
      id: 'a-backpack',
      name: '皮质双肩包',
      category: 'office',
      status: 'sold',
      purchasePrice: 1680,
      purchaseDate: daysAgoISO(700),
      soldDate: daysAgoISO(20),
      soldPrice: 920,
      targetDailyCost: 3,
      expectedDays: 560,
      imageKey: 'backpack',
    },
    {
      id: 'a-sneaker',
      name: '限量球鞋',
      category: 'blindbox',
      status: 'sold',
      purchasePrice: 1299,
      purchaseDate: daysAgoISO(260),
      soldDate: daysAgoISO(15),
      soldPrice: 1580,
      targetDailyCost: 5,
      expectedDays: 260,
      imageKey: 'sneaker',
    },
    {
      id: 'a-helmet',
      name: '碳纤维头盔',
      category: 'transport',
      status: 'sold',
      purchasePrice: 3200,
      purchaseDate: daysAgoISO(500),
      soldDate: daysAgoISO(45),
      soldPrice: 2100,
      targetDailyCost: 6,
      expectedDays: 534,
      imageKey: 'helmet',
    },
    {
      id: 'a-moto',
      name: '复古机车',
      category: 'transport',
      status: 'active',
      purchasePrice: 68000,
      purchaseDate: daysAgoISO(640),
      targetDailyCost: 80,
      expectedDays: 850,
      imageKey: 'motorcycle',
    },
    {
      id: 'a-gold',
      name: '投资金条 50g',
      category: 'uncategorized',
      status: 'active',
      purchasePrice: 38500,
      purchaseDate: daysAgoISO(390),
      targetDailyCost: 1,
      expectedDays: 36500,
      imageKey: 'gold',
      starred: true,
      note: '硬通货，不算消耗',
    },
  ];
}

export function demoWishes(): WishItem[] {
  return [
    {
      id: 'w-1',
      name: '17 Pro Max',
      targetPrice: 8999,
      saved: 4200,
      category: 'digital',
      imageKey: 'iphone',
    },
    {
      id: 'w-2',
      name: 'Max 头戴耳机',
      targetPrice: 3999,
      saved: 1200,
      category: 'digital',
      imageKey: 'headphones',
    },
    {
      id: 'w-3',
      name: 'Home 音箱',
      targetPrice: 2299,
      saved: 2299,
      category: 'home',
      imageKey: 'speaker',
    },
  ];
}

export function demoPlans(): SavingsPlan[] {
  return [
    {
      id: 's-1',
      name: '换机基金',
      targetAmount: 8999,
      currentAmount: 4200,
      deadline: daysAgoISO(-120),
    },
    {
      id: 's-2',
      name: '旅行备用金',
      targetAmount: 8000,
      currentAmount: 2650,
      deadline: daysAgoISO(-200),
    },
  ];
}
